export const countries = [
    { label: 'Select your country', value: '', code: '', phoneLength: 0 },
    { label: 'United States', value: 'US', code: '+1', phoneLength: 10 },
    { label: 'Canada', value: 'CA', code: '+1', phoneLength: 10 },
    { label: 'Brazil', value: 'BR', code: '+55', phoneLength: 11 },
    { label: 'United Kingdom', value: 'GB', code: '+44', phoneLength: 10 },
    { label: 'France', value: 'FR', code: '+33', phoneLength: 9 },
    { label: 'Germany', value: 'DE', code: '+49', phoneLength: 10 },
    { label: 'Italy', value: 'IT', code: '+39', phoneLength: 10 },
    { label: 'Spain', value: 'ES', code: '+34', phoneLength: 9 },
    { label: 'China', value: 'CN', code: '+86', phoneLength: 11 },
    { label: 'Japan', value: 'JP', code: '+81', phoneLength: 10 },
    { label: 'Australia', value: 'AU', code: '+61', phoneLength: 9 },
    { label: 'Mexico', value: 'MX', code: '+52', phoneLength: 10 },
    { label: 'Russia', value: 'RU', code: '+7', phoneLength: 10 },
    { label: 'India', value: 'IN', code: '+91', phoneLength: 10 },
    { label: 'Turkey', value: 'TR', code: '+90', phoneLength: 10 },
    { label: 'Thailand', value: 'TH', code: '+66', phoneLength: 9 },
    { label: 'Greece', value: 'GR', code: '+30', phoneLength: 10 },
    { label: 'Egypt', value: 'EG', code: '+20', phoneLength: 10 },
    { label: 'South Africa', value: 'ZA', code: '+27', phoneLength: 9 },
    { label: 'Argentina', value: 'AR', code: '+54', phoneLength: 10 },
    { label: 'Malaysia', value: 'MY', code: '+60', phoneLength: 9 },
    { label: 'Indonesia', value: 'ID', code: '+62', phoneLength: 10 },
    { label: 'Singapore', value: 'SG', code: '+65', phoneLength: 8 },
    { label: 'Netherlands', value: 'NL', code: '+31', phoneLength: 9 },
    { label: 'Switzerland', value: 'CH', code: '+41', phoneLength: 9 },
    { label: 'Portugal', value: 'PT', code: '+351', phoneLength: 9 },
    { label: 'Austria', value: 'AT', code: '+43', phoneLength: 10 },
    { label: 'Belgium', value: 'BE', code: '+32', phoneLength: 9 },
    { label: 'New Zealand', value: 'NZ', code: '+64', phoneLength: 9 },
    { label: 'Sweden', value: 'SE', code: '+46', phoneLength: 9 },
    { label: 'Norway', value: 'NO', code: '+47', phoneLength: 8 },
    { label: 'Denmark', value: 'DK', code: '+45', phoneLength: 8 },
    { label: 'Poland', value: 'PL', code: '+48', phoneLength: 9 },
    { label: 'South Korea', value: 'KR', code: '+82', phoneLength: 10 },
    { label: 'Ireland', value: 'IE', code: '+353', phoneLength: 9 },
    { label: 'Czech Republic', value: 'CZ', code: '+420', phoneLength: 9 },
    { label: 'Chile', value: 'CL', code: '+56', phoneLength: 9 },
    { label: 'United Arab Emirates', value: 'AE', code: '+971', phoneLength: 9 },
    { label: 'Saudi Arabia', value: 'SA', code: '+966', phoneLength: 9 },
    { label: 'Vietnam', value: 'VN', code: '+84', phoneLength: 10 },
    { label: 'Philippines', value: 'PH', code: '+63', phoneLength: 10 },
    { label: 'Israel', value: 'IL', code: '+972', phoneLength: 9 },
    { label: 'Hungary', value: 'HU', code: '+36', phoneLength: 9 },
    { label: 'Finland', value: 'FI', code: '+358', phoneLength: 9 },
    { label: 'Hong Kong', value: 'HK', code: '+852', phoneLength: 8 },
    { label: 'Morocco', value: 'MA', code: '+212', phoneLength: 9 },
    { label: 'Croatia', value: 'HR', code: '+385', phoneLength: 9 },
    { label: 'Iceland', value: 'IS', code: '+354', phoneLength: 7 },
    { label: 'Ukraine', value: 'UA', code: '+380', phoneLength: 9 },
    { label: 'Peru', value: 'PE', code: '+51', phoneLength: 9 },
];
